### ISSUE TITLE
[FEAT] id 값으로 엔티티 찾는 메서드들 변경

### ISSUE THREAD

**Issue by choigy1001** [Semoban/meongcare-back#103]
## Description
- soft delete 때문에 getById를 그대로 쓸 수 없음. deleted = 0 인 필드를 조건으로 추가해야함

## ToDo
- [ ] getById 메서드들 deleted 필드 추가

## ETC
-

**Comment by 0sunset0** [comment]
이거 각자 맡은 도메인 별로 수정하나요?? 아니면 근영님이 다 하실 계획이신가여??
저도 안되어 있는 곳이 많네요..ㅎㅎ
